import pandas as pd
from plotly import graph_objects as go
import plotly.express as px
import streamlit as st

st.write("# Technology and Product Analysis")

st.write("## What are projects built with?")

fig = go.Figure()
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[47.4, 50.0, 35.3, 53.3], name="PEM"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[26.3, 18.8, 14.7, 13.3], name="ALK"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[21.1, 0, 14.7, 6.7], name="SOEC"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[0, 0, 14.7, 3.3], name="AEMWE"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[5.3, 31.2, 20.5, 23.3], name="Other Electrolysis"))
fig.update_layout(title="Elecrolyser Technology over time (2021-2024)")
fig.update_layout(barmode="stack")

st.plotly_chart(fig)

st.caption(
    "Compare the share of different electrolysis technologies in PtX projects in Germany from 2021 to 2024."
)

st.write(
    "PEM dominates the project landscape in every year, ranging from about one‑third to over half of all projects. ALK loses share over time, while SOEC, AEMWE and “other” electrolysis methods gradually appear as developers test more experimental options alongside the mature technologies."
)

st.image(
    "app/files/technologies.png",
    caption="Different electrolysis technologies used in PtX projects in Germany, ALK vs PEM vs SOEC. - Image generated by Google DeepMind's Nano Banana Pro model via Gemini 3 Pro (Feb 2026).",
)

st.write(
    "The data suggests that PEM has become the workhorse technology for PtX projects in Germany.  Its flexibility, fast response and falling stack costs make it attractive where projects need to follow variable wind and solar generation.  ALK still appears in a meaningful minority of projects, but its share declines as developers prioritise controllability and grid services over purely low upfront cost.  SOEC and AEMWE remain niche, reflecting their higher technical risk and the need for more demonstration experience."
)

fig = go.Figure()
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[63.2, 81.2, 79.4, 83.3], name="H₂"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[5.3, 6.2, 11.8, 0], name="MeOH"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[21.1, 6.2, 5.9, 10.0], name="Synfuels"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[0, 0, 2.9, 3.3], name="CH₄"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[10.5, 0, 0, 0], name="Synthetic hydrocarbons (subset)"))
fig.add_trace(go.Bar(x=[2021, 2022, 2023, 2024], y=[0, 6.2, 0, 3.3], name="None"))
fig.update_layout(title="Product focus over time (2021-2024)")
fig.update_layout(barmode="stack")

st.plotly_chart(fig)

st.caption(
    "Compare the share of different PtX products in projects in Germany from 2021 to 2024."
)

st.write(
    "Across all four years, hydrogen clearly dominates the PtX product portfolio, rising from about 63% of projects in 2021 to over 83% in 2024. Synfuels and methanol appear every year but remain secondary, while methane and “no defined product yet” signal pilot and experimental projects rather than large‑scale deployment."
)

st.write("## Cumulative product picture")
st.write(
    "Cumulatively, almost four out of five PtX projects in Germany target hydrogen as their main product, with a smaller but persistent group exploring liquid e‑fuels, methanol, synthetic hydrocarbons and methane."
)

data = {
    'product': [
        'H2',
        'Synfuels (liquid e‑fuels etc.)',
        'MeOH',
        'Synthetic hydrocarbons',
        'CH₄',
        'None (not specified yet)'
    ],
    'percentage': [77.8, 10.1, 6.1, 2, 2, 2]
}
df = pd.DataFrame(data)
fig = px.pie(df, values='percentage', names='product',
             title='Total distribution of product output from 2021 to 2024')
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(
    margin=dict(t=50, b=50, l=50, r=50)  # reduce margins = bigger pie
)
st.plotly_chart(fig)

st.caption(
    "Compare the cumulative share of different PtX products in projects in Germany from 2021 to 2024."
)

st.write(
    "The combination of PEM dominance and a strong bias toward hydrogen output suggests that German PtX deployments are optimised first for flexible, grid‑coupled H₂ production rather than for complex downstream synthesis routes. Liquid synfuels and methanol appear mainly in smaller project numbers, often in demonstration settings or targeting specific industrial or transport niches."
)
st.write(
    "If this pattern continues, Germany’s near‑term PtX system will look like a hydrogen backbone with smaller satellites of methanol and e‑fuel projects attached to it. For sectors such as aviation or chemical feedstocks, this means that scaling synfuels will depend on how quickly these early, technology‑diverse pilot projects can be de‑risked and replicated."
)
