import streamlit as st  
import pandas as pd


st.write("## Technical barriers (engineering problems)")

confusion_matrix = pd.DataFrame(
    {
        "Barrier type": ["Technical challenges", "Regulatory/policy", "Economic/financial"],
        "Qualitative weight": ["High stack degradation, grid integration, materials, thermal control", "High permits, certification, unclear rules", "High CapEx, power price, CO₂ cost"],
    },
)
st.table(confusion_matrix.reset_index(drop=True))

st.write("The implementation gap in PtX projects is not caused by a single factor. Technical issues like stack degradation, grid bottlenecks and critical‑material constraints interact with regulatory and financial risks, so problems in one dimension often trigger delays in others.")
st.write("On the technical side, scaling PEM electrolysers from a few megawatts to hundreds of megawatts exposes limits in materials, cooling and system design. Uneven temperature and pressure across large stacks accelerate catalyst degradation, while strict water purity and membrane hydration requirements raise the risk that minor process deviations damage expensive components. At system level, integrating dozens of identical modules into a single plant and connecting them to stressed 110 kV networks in Lower Saxony and northern Germany creates congestion hotspots and voltage‑stability issues if load‑flow studies and grid‑friendly controls are missing.")

st.image("app/files/electrolyser-stack.png", caption="Schematic of a PEM electrolyser stack, showing the key components and their functions. - Image generated by Google DeepMind's Nano Banana Pro model via Gemini 3 Pro (Feb 2026).")

st.write("Large‑scale PtX plants stress both the equipment and the grid: operators must keep stacks within narrow thermal and chemical windows while simultaneously ensuring that 100–200 MW electrolysers do not overload local 110 kV networks.  These constraints help explain why many projects remain at feasibility stage even after several years.")

st.write("## why projects don’t get financed")
st.markdown("- Fragmented certification for green hydrogen (Guarantees of Origin not harmonised).")

st.markdown("- Weak and distorted EU ETS carbon price (free allocation for heavy industry).")
st.markdown("- Unclear legal status for hydrogen pipelines and storage (TEN‑E, national energy laws).")
st.markdown("- High electrolyser CapEx (60–80% of total plant investment).")
st.markdown("- Expensive and volatile electricity (often > 5 EUR/kg H₂ contribution).")
st.markdown("- High CO₂ feedstock costs (≈ 85–209 EUR/t via DAC, 25–135 EUR/t from flue gas plus transport).")

st.write("Even technically solid projects struggle to reach financial close. Electrolysers still account for 60–80% of plant CapEx, while electricity can represent more than half of the levelised cost of hydrogen and often pushes OpEx above 5 EUR/kg. At the same time, developers face fragmented certification rules, unclear pipeline regulation and limited long‑term support instruments, which makes it hard to sign the bankable contracts lenders expect")

st.write("When you look across all case years from 2021 to 2024, the pattern is consistent: projects accumulate in the feasibility‑study phase and comparatively few reach FID or operation. The technical section of the thesis shows how reliability concerns, grid bottlenecks and critical‑material supply add engineering risk on top of the pure economics of hydrogen production.")
st.write("The regulatory and financial analysis explains why this risk often becomes a hard stop. Weak carbon prices and fragmented Guarantees of Origin limit the premium that buyers are willing to pay, while there is no widely used instrument such as carbon contracts for difference to stabilise revenues.  Combined with high capital costs, volatile power prices and expensive CO₂ feedstock, these conditions create precisely the kind of uncertainty that keeps projects in “announced” or “feasibility” status instead of being built.")
