import streamlit as st  
import pandas as pd


st.write("## Technical barriers (engineering problems")

confusion_matrix = pd.DataFrame(
    {
        "Barrier type": ["Technical challenges", "Regulatory/policy", "Economic/financial"],
        "Qualitative weight": ["High stack degradation, grid integration, materials, thermal control", "High permits, certification, unclear rules", "High CapEx, power price, CO₂ cost"],
    },
)
st.table(confusion_matrix)

st.write("The implementation gap in PtX projects is not caused by a single factor. Technical issues like stack degradation, grid bottlenecks and critical‑material constraints interact with regulatory and financial risks, so problems in one dimension often trigger delays in others.")
st.write("On the technical side, scaling PEM electrolysers from a few megawatts to hundreds of megawatts exposes limits in materials, cooling and system design. Uneven temperature and pressure across large stacks accelerate catalyst degradation, while strict water purity and membrane hydration requirements raise the risk that minor process deviations damage expensive components. At system level, integrating dozens of identical modules into a single plant and connecting them to stressed 110 kV networks in Lower Saxony and northern Germany creates congestion hotspots and voltage‑stability issues if load‑flow studies and grid‑friendly controls are missing.")

st.image("app/files/electrolyser-stack.png", caption="Schematic of a PEM electrolyser stack, showing the key components and their functions. - Image generated by Google DeepMind's Nano Banana Pro model via Gemini 3 Pro (Feb 2026).")
