name: CI (Self-hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build

      - name: Stop old container
        run: docker compose down

      - name: Start new container
        run: docker compose up -d
